FROM alpine AS qemu

#QEMU Download
ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-aarch64.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM arm64v8/node:10
MAINTAINER Klaus Gamauf <kg@w4it.at>

# Add QEMU
COPY --from=qemu qemu-aarch64-static /usr/bin

RUN npm install -g localtunnel

ENTRYPOINT ["node", "/usr/bin/lt"]
